### ISSUE TITLE
Suggestion for extract weights for vgg16.npy

### ISSUE THREAD

**Issue by bcrevath** [yuyang-huang/keras-inception-resnet-v2#8]
Hi Yuyang,

I have obtained vgg16.npy using your extract_weights.py, by modifying it. Now i want to use load_weights.py. to convert vgg16.ckpt to hd5 format. I have attached the weights format of vgg16.npy in attachment. Please help me to modify code of load_weights.py for my requirement. Thankyou.
![code2](https://user-images.githubusercontent.com/43743070/86528031-08469e00-bec2-11ea-8278-b8b53d94fa61.PNG)
![code](https://user-images.githubusercontent.com/43743070/86528034-0977cb00-bec2-11ea-8636-4e93d5a76c09.PNG)

Regards,
Nandan

**Comment by yuyang-huang** [comment]
Hi Nandan,

To load the weights, you also need a `vgg16.py` similar to the [inception_resnet_v2.py](https://github.com/yuyang-huang/keras-inception-resnet-v2/blob/master/inception_resnet_v2.py) in this project, with **every layer named** according to the weight names in the CKPT file.

I had to extract weights from CKPT because at that time there was not an `InceptionResNetV2` model in Keras. In your case, I believe training a VGG16 using [Keras applications](https://keras.io/api/applications/) will be much easier than trying to convert a CKPT into HDF5.

**Comment by bcrevath** [comment]
Hi,
The reason I am asking is , I already have a pre-trained ckpt weights of vgg16 for my application. I need a solution to convert my ckpt weights to hd5 format.  My weights file = tusimple_lanenet_vgg.ckpt. 

Regards,
Nandan

**Comment by bcrevath** [comment]
![code3](https://user-images.githubusercontent.com/43743070/86528279-21504e80-bec4-11ea-846f-70aacd7c7f94.PNG)

I have changed the code as such to obtain vgg16 from keras

**Comment by bcrevath** [comment]
![image](https://user-images.githubusercontent.com/43743070/86528372-e3075f00-bec4-11ea-90d8-7af3f147d758.png)
